site_name: Dezzex Technology Pvt Ltd real-time messaging challenge
site_url: https://example.com
site_author: Mohamed Nesredin
site_description: >-
  This is a project provide it by Dezzex Technology Pvt Ltd to build real-time messaging app

repo_name: Mohamed-Kaizen/dezzex-technology-pvt-ltd-real-time-messaging-challenge
repo_url: https://github.com/Mohamed-Kaizen/dezzex-technology-pvt-ltd-real-time-messaging-challenge/
edit_uri: 'https://github.com/Mohamed-Kaizen/dezzex-technology-pvt-ltd-real-time-messaging-challenge/tree/master/docs'

copyright: Copyright &copy; 2020 Mohamed Nesredin

theme:
  name: material
  custom_dir: docs/overrides
  icon:
    repo: fontawesome/brands/github-alt
  features:
    - navigation.tabs
    - navigation.tabs
    - navigation.top
    - search.suggest
    - search.highlight
    - search.share
    - content.tabs.link
    - content.code.annotate
    - social
  palette:
    - media: '(prefers-color-scheme: light)'
      scheme: default
      primary: indigo
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - media: '(prefers-color-scheme: dark)'
      scheme: slate
      primary: indigo
      toggle:
        icon: material/weather-night
        name: Switch to light mode
# google_analytics:
#   - UA-XXXXXXXX-X
#   - auto

plugins:
  - search
  - git-authors:
      show_contribution: true
      show_line_count: true
      count_empty_lines: true
  - minify:
      minify_html: true
  - git-revision-date-localized:
      type: timeago
  - mkdocstrings:
      handlers:
        python:
          setup_commands:
            - import os
            - import django
            - os.environ.setdefault("DJANGO_SETTINGS_MODULE", "dezzex_technology_pvt_ltd_real_time_messaging_challenge.settings")
            - django.setup()

nav:
  - Home: 'index.md'
  - API:
      - Users:
          - API: "api/users/api.md"
          - Models: "api/users/models.md"
          - Schema: "api/users/schema.md"
          - Validators: 'api/users/validators.md'
      - Chat:
          - API: "api/chat/api.md"
          - Consumers: 'api/chat/consumers.md'
          - Models: "api/chat/models.md"
          - Schema: "api/chat/schema.md"


markdown_extensions:
  - meta
  - abbr
  - tables
  - pymdownx.snippets
  - admonition
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.tabbed:
      alternate_style: true
  - footnotes
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.smartsymbols
  - attr_list
  - def_list
  - md_in_html
  - pymdownx.tasklist:
      custom_checkbox: true
      clickable_checkbox: true

extra_css:
    - 'css/termynal.css'
    - 'css/custom.css'

extra_javascript:
    - 'https://unpkg.com/mermaid@8.4.6/dist/mermaid.min.js'
    - 'js/termynal.js'
    - 'js/custom.js'
